[workspace]
authors = ["fgvieira <1151762+fgvieira@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
name = "seqcenter"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.0.0,<3.15"
plotly = ">=6.5.0,<7"
matplotlib = ">=3.10.0,<4"
samshee = ">=0.2.0,<0.3"
pandas = ">=2.3.0,<3"
numpy = ">=2.3.0,<3"
